controller_manager:
  ros__parameters:
    update_rate: 50
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ['left_front_wheel_joint', 'left_mid_wheel_joint', 'left_rear_wheel_joint']
    right_wheel_names: ['right_front_wheel_joint', 'right_mid_wheel_joint', 'right_rear_wheel_joint']
    wheel_separation: 0.6
    wheel_radius: 0.12
    publish_rate: 50.0
    base_frame_id: base_link
    use_stamped_vel: false
    enable_odom_tf: true
    cmd_vel_timeout: 0.5

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0
        min_velocity: -1.0

    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.0
        min_velocity: -1.0
